### ISSUE TITLE
DigraphGA is buggy in neovim

### ISSUE THREAD

**Issue by hgiesel** [chrisbra/unicode.vim#31] opened 2018-12-14 13:04 UTC
I noticed that when you `<Plug>DigraphGA` you get a buggy display:

![screenshot 2018-12-14 at 14 00 27](https://user-images.githubusercontent.com/7188844/50004918-e5cff580-ffa8-11e8-9686-7976fc8d529a.png)

This was tried on a minimal setup with `unicode.vim`. Basically I first executed `<Plug>DigraphGA` on the letter a, and then on the letter gamma.
If you erase the status line before executing it the second time, it displays correctly.

As soon as it displays wrong the first time, the information will always be displayed where in the screenshot the information for gamma is displayed.

**Comment by chrisbra** [comment] 2018-12-14 16:12
Please check first with Vim. If neovim broke it, they should fix it.

**Comment by chrisbra** [comment] 2018-12-14 21:54
cannot reproduce in Vim. Closing

**Closed by chrisbra** 2018-12-14 21:54 UTC
